### ISSUE TITLE
The difference of tensorflow 1.5.0's nms and earler version?

### ISSUE THREAD

**Issue by hangkaitan** [zengarden/light_head_rcnn#16]

**Comment by zengarden** [comment]
GPU NMS needs to perform some bitwise operations on type unsigned int64, and uint64 is not supported before tf1.5. As far as i know, NMS in tf.image runs on cpu.

**Comment by hangkaitan** [comment]
Our server's system can't support tf1.5(only tf1.4), i can just use CPU NMS?

**Comment by zengarden** [comment]
em, I think TF1.4 will work fine if you adopted tf.image.nms.
