### ISSUE TITLE
training hang at restoring res101.ckpt

### ISSUE THREAD

**Issue by jwnsu** [zengarden/light_head_rcnn#17]
Tried light_head_rcnn.ori_res101.coco.ps_roialign training with 4 GPUs (same result with 1 GPU too), it simply hang at step "Restoring parameters from /home/dsu/ai/lh/data/imagenet_weights/res101.ckpt". GPUs show 207MB memory, 0% utility. A lot of CPUs/cores (about 30) running at 100%.

When kill the training, sees this error:
```
File "/home/dsu/ai/lh/experiments/my/light_head_rcnn.ori_res101.coco/dataset.py", line 129, in get_data_for_singlegpu
    img = cv2.imread(image_path, cv2.IMREAD_COLOR)

```
Same issue with light_head_rcnn.ori_res101.cocoexperiment.

ubuntu 16.04, tf1.5, cuda9, and 1080 Ti (tf1.6 has same issue, downgrade to 1.5 didn't make any difference).

anyone runs into this issue?

**Comment by zengarden** [comment]
You can run dataset.py to check if your data processing correctly. From the error, the program may hang at data io.

**Comment by jwnsu** [comment]
Thx a lot for the hint. Saw while loop in dataset's line 128, it will hang there if an image is not available (caused by config.py's train_root_folder missing training "/"). It's better to print an error message and either skip or stop.
