### ISSUE TITLE
undefined symbol when import fast_nms.so

### ISSUE THREAD

**Issue by Airpooyan** [zengarden/light_head_rcnn#29]
![image](https://user-images.githubusercontent.com/18299981/41037185-13399032-69c5-11e8-9ef2-513f006d71b3.png)
I have run the make.sh in lib directory and all succeeded
when I run test.py -d 0 -se 26 it reported this error
I googled many times but found no useful solutions for this problem
How can I figure this out?

**Comment by wsycl** [comment]
I also met the same error, Have you solved this problem? I hope you can share with us. Thx
