### ISSUE TITLE
g++ error

### ISSUE THREAD

**Issue by powermano** [zengarden/light_head_rcnn#32]
when i run the bash make.sh, the following error occurs:
~/light_head_rcnn/lib
~/light_head_rcnn/lib/lib_kernel/lib_fast_nms ~/light_head_rcnn/lib
make.sh: 5: make.sh: nvcc: not found
g++: error: nms_op.cu.o: No such file or directory

what is the problem

**Comment by powermano** [comment]
When i solve above problem, new issue comes:

    fatal error: cuda/include/cuda.h: No such file or directory
And i find the cuda.h at /usr/local/cuda-9.0/include/cuda.h ,  what can i do next? How export the CPATH?

**Comment by wm10240** [comment]
@powermano I also have same error, like：
```
cuda_kernel_helper.h:24:31: fatal error: cuda/include/cuda.h: No such file or director
```
I change the code in cuda_kernel_helper.h:
```
#include "cuda/include/cuda.h" to #include "/usr/local/cuda/include/cuda.h"
``` 
and it works
