### ISSUE TITLE
iteration stopped randomly

### ISSUE THREAD

**Issue by xtanitfy** [zengarden/light_head_rcnn#4]
When I trained for an indefinite number of iterations, the iteration stopped and no reason was found.I  use one 1080TI and use my dataset converted od format.It looks like  stopping on the function of 'socket.recv'.Has been excluded from stopping in ‘get_data_for_singlegpu’ function，  Because I stopped it and print in every possible exit that not occured.

**Comment by zengarden** [comment]
@xtanitfy Did u use the recent python package msgpack and msgpack-numpy? Could u show me detail logs?

**Comment by xtanitfy** [comment]
Only iterative information, no error message。I will try to install msgpack-numpy。

**Comment by xtanitfy** [comment]
I will try again and I will not stop, thank you for your reply

**Comment by Jerry3062** [comment]
HI
    I think I met the same problem. Have you solve it?  If you solved, Could you please tell me how you solve it. Thinks.

**Comment by Jerry3062** [comment]
@xtanitfy 
HI
I think I met the same problem. Have you solve it? If you solved, Could you please tell me how you solve it. Thinks.

**Comment by xtanitfy** [comment]
@Jerry3062 Maybe you should check your dataset.After finding the error of transforming my dataset,I solevd the problem!

**Comment by dedoogong** [comment]
I had same problem and solved it too. The problem came from duplicating one same image file path in several places in odgt file which is generated by my own python script. So there must be a race condition accessing one same image from 16 batch processes and then waiting forever.

**Comment by dedoogong** [comment]
@xtanitfy I had same problem and solved it too. The problem came from duplicating one same image file path in several places in odgt file which is generated by my own python script. So there must be a race condition accessing one same image from 16 batch processes and then waiting forever.
